INSERT INTO TB_CATEGORIA(ID_CATEGORIA,NOME_DESCRICAO)VALUES(1,'CATEGORIA 1');
INSERT INTO TB_CATEGORIA(ID_CATEGORIA,NOME_DESCRICAO)VALUES(2,'CATEGORIA 2');
INSERT INTO TB_CATEGORIA(ID_CATEGORIA,NOME_DESCRICAO)VALUES(3,'CATEGORIA 3');